namespace ACE.SinglePlayer.Mods;

public static class CuratedModCatalog
{
    public static IReadOnlyList<ModCatalogEntry> Entries { get; } =
        AquafirSampleCatalog.Entries.Concat(new[]
        {
            new ModCatalogEntry(
                "titaniumweiner.ace-unique-weenies-proc",
                "Expanded Cast on Strike",
                "titaniumweiner",
                "Enables cast-on-strike procs on non-Aetheria equipped items such as the jewelry, armor, and weapons used by ACEUniqueWeenies content.",
                "Replaces ACE's Aetheria-only equipped-proc pass with the filter documented by ACEUniqueWeenies: the item must have a proc, must not be cloak weave proc type 1, and must match the current self-target mode. The package changes server combat behavior only; import compatible item SQL separately through Custom Weenies. It intentionally matches the documented filter exactly, including processing an active proc weapon again if that weapon is also present in EquippedObjects.",
                "https://github.com/titaniumweiner/ACEUniqueWeenies",
                ModCatalogAvailability.Preview,
                ModDataImpact.SettingsOnly,
                ModRemovalPolicy.Safe,
                "Safe to turn off after a server restart. Imported items remain in the world, but their non-Aetheria equipped procs stop working. Earlier combat results are not reversed.",
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 preview port",
                PackageRelativePath: @"Packages\titaniumweiner.ace-unique-weenies-proc-1.0.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.ACEUniqueWeeniesProc",
                PreviewNotice: "The package builds, loads, targets the pinned TryProcEquippedItems signature, and passes filter and removal tests. Its proc frequency and interactions with every custom item have not been thoroughly tested in game."),
            new ModCatalogEntry(
                "opendereth.unlimited-stat-augmentation-gems",
                "Unlimited Stat Augmentation Gems",
                "OpenDereth",
                "Lets characters use Strength, Endurance, Coordination, Quickness, Focus, and Self augmentation gems without the normal shared usage limit, while every innate stat remains capped at 100.",
                "Only the six innate-stat gem limits change. Gems still cost experience and are consumed normally. Skill, resistance, pack, burden, critical, damage, and every other augmentation keep their stock ACE limits. Extra stat gains are saved on the character and are not removed if the mod is later turned off.",
                "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.UnlimitedStatAugmentation",
                ModCatalogAvailability.Preview,
                ModDataImpact.CharacterData,
                ModRemovalPolicy.ChangesRemain,
                "Back up before enabling. Turning the mod off restores the normal shared limit after restart, but stat increases already earned remain on each character.",
                ConflictIds: new[] { "aquafir.quality-of-life" },
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 preview mod",
                PackageRelativePath: @"Packages\opendereth.unlimited-stat-augmentation-gems-1.0.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.UnlimitedStatAugmentation",
                PreviewNotice: "The package builds, loads, patches the pinned ACE safety-cap getter, preserves every non-stat augmentation limit, and passes enable/disable tests. Full gem acquisition and character-save behavior have not yet been thoroughly tested in game."),
            new ModCatalogEntry(
                "opendereth.unlimited-skill-specializations",
                "Unlimited Skill Specializations",
                "OpenDereth",
                "Removes ACE's 70-credit total specialization ceiling so characters can specialize additional trained skills when they have enough available skill credits.",
                "Only the total specialized-credit cap is removed. Each skill must still be trained, its normal specialization cost is still required and deducted, and rank, experience, heritage-cost, and skill-lowering behavior remain unchanged. ACE's administrator skill-credit verifier accepts over-cap characters while the mod is enabled. Over-cap specializations are saved on the character and are not automatically removed if the mod is turned off.",
                "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.UnlimitedSkillSpecializations",
                ModCatalogAvailability.Preview,
                ModDataImpact.CharacterData,
                ModRemovalPolicy.ChangesRemain,
                "Back up before enabling. Turning the mod off restores the normal 70-credit ceiling after restart, but existing over-cap specializations remain until lowered normally.",
                ConflictIds: new[] { "aquafir.quality-of-life" },
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 preview mod",
                PackageRelativePath: @"Packages\opendereth.unlimited-skill-specializations-1.0.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.UnlimitedSkillSpecializations",
                PreviewNotice: "The package builds, loads, targets the pinned Gem of Enlightenment and administrator verifier signatures, replaces only their 70-credit cap constants, and passes removal tests. Full in-game specialization, save, restart, and rollback behavior have not yet been thoroughly tested."),
            new ModCatalogEntry(
                "opendereth.universal-loot-luck",
                "All-Tier Salvage & Loot Luck",
                "OpenDereth",
                "Lets every equipment-loot tier roll the complete ACE material pool, with optional independent controls for loot quality, generated-loot chances, trophies, and rares.",
                "By default, only material availability changes: item categories keep their compatible material tables, but their normalized tier 1-6 rows are combined before the material roll. The included Settings.json leaves all luck values at stock ACE behavior until changed. Optional settings add a bounded loot-quality bias or multiply generated-loot category chances, the server's existing trophy rate, and the first rare-eligibility roll without overwriting server configuration.",
                "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.UniversalLootLuck",
                ModCatalogAvailability.Preview,
                ModDataImpact.CharacterData,
                ModRemovalPolicy.ChangesRemain,
                "Safe to disable after a server restart, but materials and quality already generated on saved items remain. Back up before testing large luck multipliers.",
                ConflictIds: new[] { "aquafir.expansion" },
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 preview mod",
                PackageRelativePath: @"Packages\opendereth.universal-loot-luck-1.0.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.UniversalLootLuck",
                PreviewNotice: "The package builds, loads, targets the pinned ACE loot, material, trophy, and rare signatures, validates bounded settings, and passes profile, weighted-roll, multiplier, and removal tests. Every material table and high-multiplier combination has not yet been thoroughly tested in game."),
            new ModCatalogEntry(
                "opendereth.three-imbues",
                "Three Imbues",
                "OpenDereth",
                "Allows eligible items to receive as many as three distinct standard salvage imbues, such as Armor Rending, Critical Strike, and Crippling Blow on one compatible weapon.",
                "ACE's normal item eligibility, ten-tinker limit, workmanship, tinkering skill, success chance, salvage consumption, and failure-destruction rules remain active. Reapplying the same effect is rejected. Effects are stored in ACE's first three persistent imbue slots, and the runtime combines those slots for weapon and equipped-defense calculations. Settings.json may lower the limit to one or two but cannot raise it above the tested three-slot cap.",
                "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.MultiImbue",
                ModCatalogAvailability.Preview,
                ModDataImpact.CharacterData,
                ModRemovalPolicy.DoNotRemove,
                "Back up first. Do not permanently remove the mod while characters own multi-imbued items. Secondary effects remain saved but become inactive under stock ACE until the mod is enabled again.",
                ConflictIds: new[] { "aquafir.tinkering" },
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 preview mod",
                PackageRelativePath: @"Packages\opendereth.three-imbues-1.0.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.MultiImbue",
                PreviewNotice: "The package builds, loads, maps all thirteen supported material imbues, enforces distinct effects and a hard three-slot cap, targets the pinned ACE recipe, mutation, weapon, and defense signatures, and passes settings, rule, patch, removal, and package tests. The complete in-game item, foolproof-salvage, appraisal, failure-destruction, and mod-interaction matrix has not yet been thoroughly tested."),
            new ModCatalogEntry(
                "opendereth.housing-upgrade-pack",
                "Housing Upgrade Pack",
                "OpenDereth",
                "Expands the item and pack capacity of Apartment, Cottage, Villa, and Mansion storage chests and removes hooked-item caps, with optional maintenance, mansion-rank, and house-purchase timer controls.",
                "Storage upgrades and both total and category hook-limit overrides are enabled by default. Settings.json provides separate, disabled-by-default options to make housing maintenance-free, ignore mansion allegiance-rank requirements, and remove the 15-day account-age and 30-day repurchase timers. The mansion option preserves the separate monarch requirement, and the hook option does not create new physical hook points. Runtime overrides do not rewrite ACE server configuration.",
                "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.HousingUpgradePack",
                ModCatalogAvailability.Preview,
                ModDataImpact.WorldData,
                ModRemovalPolicy.ChangesRemain,
                "Back up first. Disabling the mod restores stock capacities and rules. Excess chest contents are not deleted, but an overfilled chest cannot accept more items until reduced. A mansion retained through the rank override can become subject to eviction after stock rank checks return.",
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 preview mod",
                PackageRelativePath: @"Packages\opendereth.housing-upgrade-pack-1.0.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.HousingUpgradePack",
                PreviewNotice: "The package builds, loads, targets the pinned ACE storage and property-manager signatures, validates all capacity profiles, isolates each optional rule, and passes clean-removal tests. Every house layout and over-cap removal scenario has not yet been thoroughly tested in game."),
            new ModCatalogEntry(
                "opendereth.landblock-summon-balance",
                "Landblock Summon Balance",
                "OpenDereth",
                "Temporarily weakens or strengthens player-owned combat summons while they fight in explicitly tagged landblocks, without changing summon weenies or world data.",
                "Settings.json supports named landblock and exact-cell zones with independent physical damage, direct spell damage, physical attack skill, physical defense skill, and damage-taken multipliers. Opponent-based matching prevents a summon from bypassing a zone by standing across its boundary. Developer commands report the current landblock, list zones, and safely reload validated settings. The included example is disabled, so installation alone changes nothing.",
                "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.LandblockSummonBalance",
                ModCatalogAvailability.Preview,
                ModDataImpact.SettingsOnly,
                ModRemovalPolicy.Safe,
                "Safe to disable after a server restart. All multipliers are calculated at attack time and no character, summon, weenie, or world values are rewritten.",
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 preview mod",
                PackageRelativePath: @"Packages\opendereth.landblock-summon-balance-1.0.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.LandblockSummonBalance",
                PreviewNotice: "The package builds, loads, validates landblock and exact-cell rules, targets the pinned ACE physical, evasion, and direct spell-damage signatures, and passes resolution, scaling, command, and removal tests. Every summon, custom spell, dungeon boundary, and mod interaction has not yet been thoroughly tested in game."),
            new ModCatalogEntry(
                "opendereth.aquafir-creature-variants",
                "Aquafir Creature Variants",
                "Aquafir and OpenDereth",
                "Randomly gives eligible ordinary monsters one or more of eighteen configurable, stackable combat variants adapted from Aquafir's experimental ACE.BaseMod creature samples.",
                "The reviewed runtime-only port includes Accurate, Berserker, Comboer, Drainer, Duelist, Evader, Exploder, Healer, Shielded, SpellBreaker, Stomper, Vampire, Rogue, Horde, Puppeteer, Boss, Tank, and Stunner. The visible test profile gives 50% of eligible creatures a variant and permits distinct variants to stack, with a 50% additional-variant roll and a cap of three; all values are configurable. Powerful encounter variants have lower random weights. Rogue never drops equipment, Horde uses a finite health model, Puppeteer creates temporary zero-reward illusions, Boss replaces bullet hell with bounded special casts, Tank performs explicit redirection, and Stunner restores prior frozen state.",
                "https://github.com/aquafir/ACE.BaseMod/tree/41c2728fc0e4fb96d06b4e7949ca369ed5be9621/Samples/Expansion/Creatures",
                ModCatalogAvailability.Preview,
                ModDataImpact.SettingsOnly,
                ModRemovalPolicy.Safe,
                "Safe to disable after a server restart. Traits and name prefixes exist only on live creature objects; no weenie, character, or world database row is rewritten.",
                ConflictIds: new[] { "aquafir.expansion" },
                TargetAceVersion: "ACE.Server 1.1 / OpenDereth",
                TargetFramework: ".NET 10 reviewed port of .NET 8 samples",
                PackageRelativePath: @"Packages\opendereth.aquafir-creature-variants-1.2.0-sp1.zip",
                PortSourceUrl: "https://github.com/titaniumweiner/OpenDereth/tree/main/Source/ACE.SinglePlayer.Mods.AquafirCreatureVariants",
                PreviewNotice: "The package builds, loads, validates settings, weighted selection, and distinct capped stacking, targets the pinned ACE creature factory, damage, evasion, heartbeat, attribute, vital, scale, XP, and spell-resistance signatures, and passes clean-removal tests. The full stacked-combination, custom-creature, spell, dungeon, and combat-mod matrix has not yet been thoroughly tested in game."),
            new ModCatalogEntry(
                "optimshi.custom-clothing-base",
                "CustomClothingBase",
                "OptimShi",
                "Loads custom server-side ClothingTable entries from JSON files, enabling new clothing colors and appearance combinations without client DAT updates.",
                "The official v1.11 package can merge or replace ClothingTable entries, export entries with @clothingbase-export, and reload its cache with @clear-clothing-cache. Place custom JSON files in the installed mod's json folder. The upstream repository currently has no LICENSE file; redistribution is based on OptimShi's permission reported by the OpenDereth project maintainer.",
                "https://github.com/OptimShi/CustomClothingBase",
                ModCatalogAvailability.Preview,
                ModDataImpact.WorldData,
                ModRemovalPolicy.DoNotRemove,
                "Back up first. Do not disable or remove this mod while saved items or world content refer to custom ClothingBase IDs.",
                TargetAceVersion: "Official v1.11 binary load-tested with ACE.Server 1.1 / .NET 10",
                TargetFramework: ".NET 8 upstream binary hosted by .NET 10",
                PackageRelativePath: @"Packages\optimshi.custom-clothing-base-1.11-upstream.zip",
                PreviewNotice: "OptimShi's unmodified official v1.11 package passed an isolated load test with the bundled ACE server. Clothing behavior, custom JSON content, cache reloads, and saved-world compatibility have not been thoroughly tested in game.")
        }).ToArray();
}
